version: '3'
services:
  app:
    #빌드된 태그에 따른 이미지 명 수정 필요
    #배포버전은 시크릿 키로 자동 설정되게 처리함
    image: delivery1010:0.5
    ports:
      - '3000:3000'
    environment:
      - DB_PORT=3306
      - DB_HOST=delivery1010-mysql-2.csghjebsa21j.ap-northeast-2.rds.amazonaws.com
      - DB_USERNAME=admin
      - DB_PASSWORD=delivery1010!#
      - DB_DATABASE=delivery1010
